### ISSUE TITLE
Not enough memory to send instant messages, concurrent 30 sending instant messages caused memory overflow

### ISSUE THREAD

**Issue by wangwangwawng** [pjsip/pjproject#2343] opened 2020-03-13 03:02 UTC
Insufficient memory to send instant messages, sending 30 instant messages causes memory overflow, I hope it can support up to 500 concurrent
The error message is as follows
pjsua_im_send(acc->getId(), &to, &mime_type, &content, &msg_data, user_data)
Code:        70007
Description: Not enough memory (PJ_ENOMEM)
Location:    ..\src\pjsua2\presence.cpp:208

**Comment by sauwming** [comment] 2020-03-17 03:36
Duplicate of #2348. Closing this.

**Closed by sauwming** 2020-03-17 03:36 UTC
Labels: type: bug
