### ISSUE TITLE
extra audio device , but  alsa_dev.c ca_thread_func: overrun! audio latency video(video quicker than audio)! help me!

### ISSUE THREAD

**Issue by tjyuanxi** [pjsip/pjproject#3090] opened 2022-04-27 15:27 UTC
### Describe the bug

My sip is peer to peer without register! I used "class extraaudiodevice" according to your prompt, but there was another problem: "alsa_dev.c pb_thread_func: underrun!
22:35:14.339 alsa_dev.c ca_thread_func: overrun!
scombdb-dn Underflow, buf_ cnt=173, will generate 1 frame”。

At the same time, the problem of sound lagging behind video still exists, and I don't know whether the sound lagging behind is related to the video 3S and the log prompt.
How can I analyze and solve this problem? I'm very anxious. If you have any offense, please forgive me.

### Steps to reproduce

Thank you very much. My sip is peer to peer without register! I used "class extraaudiodevice" according to your prompt, but there was another problem: "alsa_dev.c pb_thread_func: underrun!
22:35:14.339 alsa_dev.c ca_thread_func: overrun!
scombdb-dn Underflow, buf_ cnt=173, will generate 1 frame”。

At the same time, the problem of sound lagging behind video still exists, and I don't know whether the sound lagging behind is related to the video 3S and the log prompt.
How can I analyze and solve this problem? I'm very anxious. If you have any offense, please forgive me
The screenshot below is a snippet of my code：
![image](https://user-images.githubusercontent.com/34560457/165554318-e135a6d2-0bf8-4247-bbab-fd1dc3d446eb.png)

### PJSIP version

2.12

### Context

![image](https://user-images.githubusercontent.com/34560457/165554357-aa4435d3-354f-4e89-b594-91d9c7b6736f.png)
Thank you very much. My sip is peer to peer without register! I used "class extraaudiodevice" according to your prompt, but there was another problem: "alsa_dev.c pb_thread_func: underrun!
22:35:14.339 alsa_dev.c ca_thread_func: overrun!
scombdb-dn Underflow, buf_ cnt=173, will generate 1 frame”。

At the same time, the problem of sound lagging behind video still exists, and I don't know whether the sound lagging behind is related to the video 3S and the log prompt.
How can I analyze and solve this problem? I'm very anxious. If you have any offense, please forgive me
The screenshot below is a snippet of my code：
![image](https://user-images.githubusercontent.com/34560457/165554318-e135a6d2-0bf8-4247-bbab-fd1dc3d446eb.png)

### Log, call stack, etc

```shell
Here is my log:
22:00:52.583 alsa_dev.c ...open_capture: buffer size set to: 1600
22:00:52.583 alsa_dev.c ...open_capture: capture_latency set to: 100 ms
22:00:52.710 pjsua_aud.c ...Extra sound device created
22:00:52.711 alsa_dev.c !pb_thread_func(1590): Started
22:00:52.711 alsa_dev.c ca_thread_func(1591): Started
22:00:52.713 pjsua2_ddapi.c !...pjcall_get_remote_acc_info.str_acct:26371290, n_port:5060, str_ip:192.168.31.130, remoteUri:sip:26371290@192.168.31.130, remoteContact:sip:26371290@192.168.31.130:5060;ob, 024bf090426edab2cd38167d30addc58, 378
onCallState:0, 26371290, 192.168.31.130, 5060, 0, 024bf090426edab2cd38167d30addc58
hashkey is DFD2AJDL722400001
{
"transaction_id" : "024bf090426edab2cd38167d30addc58"
}

4ffa481f0bcf4925b75b53fe80da5794
1483811049
sign is 0b91041c6c44b67b5a0fd0ee35e6b54a eyJhbGciOiJIUzUxMiJ9.eyJ2ZXIiOjMsImNpZCI6IkMyOEZBMTdFM0U2Nzc0MkQ1OUNBOERDQ0MyNkYzMDcyOCIsInRva2VuIjoiN2FmNzY0NDA1ZGM2NzdjYTIxNTAzMmY3YWIxNTY0YjQiLCJpYXQiOjE2NTA3MjI0NTgsImV4cCI6MTY1MDgwODg1OH0.RpW1TvVGWmGgmB1B_k4bRNlvReevTO69_tfJVu6YW4rQqsT8Zh5yyucYleV3cAUs0rQBVTx8OjFxjXoVpjIW8Q
22:00:52.715 alsa_dev.c !pb_thread_func: underrun!
22:00:52.716 alsa_dev.c pb_thread_func: underrun!
22:00:52.716 alsa_dev.c pb_thread_func: underrun!
22:00:52.716 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.717 alsa_dev.c pb_thread_func: underrun!
22:00:52.717 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.718 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.719 alsa_dev.c pb_thread_func: underrun!
22:00:52.719 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.719 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.721 alsa_dev.c pb_thread_func: underrun!
22:00:52.721 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.722 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.722 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.723 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.724 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.724 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:52.725 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
http retcode:200
nRingingInfo resp {"code":0,"msg":"","memo":"","object":{"sip_host":"10.0.1.213","sip_port":"5060","sip_no":"79656911","sip_pwd":"68916516","is_online":true,"max_duration":90,"device_type":1,"caller_pic":"https://doordustorage.oss-cn-shenzhen.aliyuncs.com/caller/BDD4001610-0955/2021/12/06/fdf2e2f8a94ce3433e4240ddcc39b370.jpg","who_is_that":"浦东一号"}}
22:00:53.060 alsa_dev.c !pb_thread_func: underrun!
22:00:53.061 pjsua_aud.c !...Conf connect: 2 --> 1
22:00:53.061 alsa_dev.c !pb_thread_func: underrun!
22:00:53.061 scombdb-up !Underflow, buf_cnt=1, will generate 1 frame
22:00:53.061 conference.c !....Port 2 (ring) transmitting to port 1 (scomb-rev)
22:00:53.061 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:53.062 alsa_dev.c pb_thread_func: underrun!
22:00:53.062 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:53.063 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:53.063 alsa_dev.c pb_thread_func: underrun!
22:00:53.063 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:53.065 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:53.066 alsa_dev.c pb_thread_func: underrun!
ZKCameraView::setPosition left: 0, top: 0, width: 800, height: 600
22:00:53.070 udp0xf1920 !...UDP media transport created
22:00:53.070 scombdb-up !Underflow, buf_cnt=1, will generate 1 frame
22:00:53.070 scombdb-up Underflow, buf_cnt=1, will generate 1 frame
22:00:53.071 udp0xf56e0 !...UDP media transport created
22:00:53.072 scombdb-up !Underflow, buf_cnt=1, will generate 1 frame

22:35:14.269 alsa_dev.c ca_thread_func: overrun!
22:35:14.339 alsa_dev.c ca_thread_func: overrun!
22:35:14.409 alsa_dev.c ca_thread_func: overrun!
22:35:14.479 alsa_dev.c ca_thread_func: overrun!
22:35:14.549 alsa_dev.c ca_thread_func: overrun!
22:35:14.619 alsa_dev.c ca_thread_func: overrun!
22:35:14.689 alsa_dev.c ca_thread_func: overrun!
22:35:14.759 alsa_dev.c ca_thread_func: overrun!
```

**Comment by sauwming** [comment] 2023-02-02 10:14
I would suggest to test first without video and extra audio device and see whether everything works fine. Then add extra audio device. Then add video.

As the issue is a while ago, I'm going to close this first. You can reopen if the issue persists.

**Closed by sauwming** 2023-02-02 10:14 UTC
