### ISSUE TITLE
 '../src/pj/os_core_unix.c:1270: pj_status_t pj_mutex_lock(pj_mutex_t *): assertion "mutex" failed'

### ISSUE THREAD

**Issue by gopipeddisetti** [pjsip/pjproject#2543] opened 2020-10-09 08:48 UTC
**Describe the bug**
 '../src/pj/os_core_unix.c:1270: pj_status_t pj_mutex_lock(pj_mutex_t *): assertion "mutex" failed'

2020-10-09 13:39:50.434 19963-19963/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG: Build fingerprint: 'xiaomi/jasmine/jasmine_sprout:9/PKQ1.180904.001/V10.0.14.0.PDIMIXM:user/release-keys'
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG: Revision: '0'
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG: ABI: 'arm64'
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG: pid: 19715, tid: 19934, name: Thread-50  >>> com.telebu.ping <<<
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG: Abort message: '../src/pj/os_core_unix.c:1270: pj_status_t pj_mutex_lock(pj_mutex_t *): assertion "mutex" failed'
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x0  0000000000000000  x1  0000000000004dde  x2  0000000000000006  x3  0000000000000008
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x4  8000000080808080  x5  8000000080808080  x6  8000000080808080  x7  0000000000000008
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x8  0000000000000083  x9  c42b948a2f9f0536  x10 0000000000000000  x11 fffffffc7ffffbdf
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x12 0000000000000001  x13 000000005f801acd  x14 0009ee0396526d00  x15 00008c2a29546fb0
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x16 0000007bf6aa92b8  x17 0000007bf69caa50  x18 0000000000000001  x19 0000000000004d03
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x20 0000000000004dde  x21 0000007b52b75c00  x22 0000007b489fdef0  x23 0000007b5775dac0
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x24 000000000000000c  x25 0000007b489ff588  x26 0000007b52b75ca0  x27 0000000000000003
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     x28 0000007b489fdc20  x29 0000007b489fdab0
2020-10-09 13:39:50.435 19963-19963/? A/DEBUG:     sp  0000007b489fda70  lr  0000007bf69bc084  pc  0000007bf69bc0ac

2020-10-09 13:39:50.498 19963-19963/? A/DEBUG: backtrace:
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #00 pc 00000000000220ac  /system/lib64/libc.so (abort+116)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #01 pc 0000000000022424  /system/lib64/libc.so (__assert2+52)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #02 pc 0000000000449634  /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/lib/arm64/libpjsua2.so (pj_mutex_lock+88)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #03 pc 000000000024ebf4  /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/lib/arm64/libpjsua2.so (pj::Endpoint::libIsThreadRegistered()+40)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #04 pc 00000000001dfe90  /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/lib/arm64/libpjsua2.so (Java_org_pjsip_pjsua2_pjsua2JNI_Endpoint_1libIsThreadRegistered+56)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #05 pc 000000000055dfe0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #06 pc 000000000055524c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #07 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #08 pc 000000000027f230  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #09 pc 0000000000279244  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #10 pc 0000000000525c40  /system/lib64/libart.so (MterpInvokeStatic+204)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #11 pc 0000000000547814  /system/lib64/libart.so (ExecuteMterpImpl+14612)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #12 pc 00000000003dcbf8  /dev/ashmem/dalvik-classes3.dex extracted in memory from /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/base.apk!classes3.dex (deleted) (org.pjsip.pjsua2.Endpoint.libIsThreadRegistered+4)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #13 pc 0000000000252f48  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1997279576+488)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #14 pc 0000000000258a3c  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #15 pc 0000000000279228  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #16 pc 000000000052473c  /system/lib64/libart.so (MterpInvokeVirtual+588)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #17 pc 0000000000547694  /system/lib64/libart.so (ExecuteMterpImpl+14228)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #18 pc 00000000001a5da2  /dev/ashmem/dalvik-classes3.dex extracted in memory from /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/base.apk!classes3.dex (deleted) (com.telebu.sip.SipService.checkThread+18)
2020-10-09 13:39:50.498 19963-19963/? A/DEBUG:     #19 pc 0000000000252f48  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1997279576+488)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #20 pc 0000000000258a3c  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #21 pc 0000000000279228  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #22 pc 0000000000525c40  /system/lib64/libart.so (MterpInvokeStatic+204)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #23 pc 0000000000547814  /system/lib64/libart.so (ExecuteMterpImpl+14612)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #24 pc 000000000033fab0  /dev/ashmem/dalvik-classes3.dex extracted in memory from /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/base.apk!classes3.dex (deleted) (media.monitoring.CallMediaMonitor.shouldBeMonitoringMedia)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #25 pc 0000000000252f48  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1997279576+488)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #26 pc 0000000000258a3c  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #27 pc 0000000000279228  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #28 pc 0000000000525a7c  /system/lib64/libart.so (MterpInvokeDirect+296)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #29 pc 0000000000547794  /system/lib64/libart.so (ExecuteMterpImpl+14484)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #30 pc 000000000033feb8  /dev/ashmem/dalvik-classes3.dex extracted in memory from /data/app/com.telebu.ping-F5NV_DjU1ccEeUuaHsBTdA==/base.apk!classes3.dex (deleted) (media.monitoring.CallMediaMonitor.run)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #31 pc 0000000000252f48  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1997279576+488)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #32 pc 0000000000258a3c  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #33 pc 0000000000279228  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #34 pc 00000000005256b8  /system/lib64/libart.so (MterpInvokeInterface+1392)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #35 pc 0000000000547894  /system/lib64/libart.so (ExecuteMterpImpl+14740)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #36 pc 00000000000dff84  /system/framework/boot-core-oj.vdex (java.lang.Thread.run+12)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #37 pc 0000000000252f48  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1997279576+488)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #38 pc 0000000000514ff0  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #39 pc 000000000055e0fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #40 pc 0000000000554f88  /system/lib64/libart.so (art_quick_invoke_stub+584)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #41 pc 00000000000cf6c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #42 pc 000000000045c8a4  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #43 pc 000000000045d960  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #44 pc 00000000004887f4  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #45 pc 00000000000920a8  /system/lib64/libc.so (__pthread_start(void*)+36)
2020-10-09 13:39:50.499 19963-19963/? A/DEBUG:     #46 pc 0000000000023968  /system/lib64/libc.so (__start_thread+68)

- PJSIP
  - version: 2.10
  - related third party libraries & versions: OpenSSL 1.0.2g

**Smartphone (please also complete the following information):**

- Device: [Android Xiaomi 9]

This crash happening frequently when we making continuous calls and delete the account and Endpoint.

Please help me, Thanks

**Comment by sauwming** [comment] 2020-10-12 03:14
Make sure that the Endpoint instance as well as the Account is still valid whenever there is a call (or if the cleanup of a call is still in progress).
And unless there's a strong reason (such as library restart, shutdown, or ip change), normally you don't need to delete account or endpoint.

If the issue still persists, please let us know the specific steps to reproduce the issue, as well as the accompanying PJSIP log (as a text attachment).

**Comment by sauwming** [comment] 2020-11-04 07:58
Closing this due to lack of further info. If you have additional details, please reopen and post it.

**Closed by sauwming** 2020-11-04 07:58 UTC
