### ISSUE TITLE
The network was already in a bad state since 22:20:39, causing the subsequent INVITE and UPDATE not to be responded. So the ip change will naturally fail with PJ_EINVALIDOP due to pending re-INVITE.

### ISSUE THREAD

**Issue by xuan6zm** [pjsip/pjproject#3793] opened 2023-11-30 03:23 UTC
The network was already in a bad state since 22:20:39, causing the subsequent INVITE and UPDATE not to be responded. So the ip change will naturally fail with PJ_EINVALIDOP due to pending re-INVITE.

Not sure what we can do here. I would suggest to detect the network failure earlier.

_Originally posted by @sauwming in https://github.com/pjsip/pjproject/issues/3749#issuecomment-1784430749_
            
When the call is switched from network A to network B, the ip_change method returns 0 or 70013. At this time, after switching, it is in a lost state;

Switching back to network A again and calling ip_change will also return 0 or 70013; At this point, the conversation is normal

How to solve the above lost contact state?

**Comment by sauwming** [comment] 2023-12-26 07:37
Duplicate of #3803?

**Closed by sauwming** 2023-12-26 07:37 UTC
