### ISSUE TITLE
[pjsip] libRegisterThread before calling any pjlib

### ISSUE THREAD

**Issue by kazimdsaidul** [pjsip/pjproject#4202] opened 2024-12-08 13:03 UTC
### Describe the bug

2024-11-10 13:18:59.695 10038-10048 libc                    com.test.sip                          A  ../src/pj/os_core_unix.c:859: pj_thread_t *pj_thread_this(void): assertion "!"Calling pjlib from unknown/external thread. You must " "register external threads with pj_thread_register() " "before calling any pjlib functions."" failed
2024-11-10 13:18:59.696 10038-10048 libc                     com.test.sip                          A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 10048 (FinalizerDaemon), pid 10038 (com.nex.sip)

### Steps to reproduce

Sometime only this error found in apps

### PJSIP version

2.13

### Context

2024-11-10 13:18:59.695 10038-10048 libc                    com.test.sip                          A  ../src/pj/os_core_unix.c:859: pj_thread_t *pj_thread_this(void): assertion "!"Calling pjlib from unknown/external thread. You must " "register external threads with pj_thread_register() " "before calling any pjlib functions."" failed
2024-11-10 13:18:59.696 10038-10048 libc                     com.test.sip                          A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 10048 (FinalizerDaemon), pid 10038 (com.nex.sip)

### Log, call stack, etc

```shell
2024-11-10 13:18:59.695 10038-10048 libc                    com.test.sip                          A  ../src/pj/os_core_unix.c:859: pj_thread_t *pj_thread_this(void): assertion "!"Calling pjlib from unknown/external thread. You must " "register external threads with pj_thread_register() " "before calling any pjlib functions."" failed
2024-11-10 13:18:59.696 10038-10048 libc                     com.test.sip                          A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 10048 (FinalizerDaemon), pid 10038 (com.nex.sip)
```

**Comment by sauwming** [comment] 2024-12-09 01:55
Duplicate of #4193

**Closed by sauwming** 2024-12-09 01:55 UTC
