### ISSUE TITLE
how to convert video file to hd quality on pjsua2 Pjsip android sample App ? 

### ISSUE THREAD

**Issue by martsa** [pjsip/pjproject#2613] opened 2020-12-24 10:07 UTC
Current default sample Android pjsip pjsua2 sample app sends  a very bad video quality and wish to improve them to atleast Hd quality. I have tried using below methods , but it keep on showing a very low video quality. How can i improve outgoing video quality.  This sample app is able to receive upto 355 * 288 video quality  from other sip video call ,but it sends a very poor video quality.
Currently i have tried to achieve hd video by updating  below value from MediaFormatvideo file , just before making outgoing call.  And it doesnt help at all to improve outgoing video .  Am i updating those attribute at wrong places ? 

Currently it sending video quality below 192 * 144 and doesnt accept above 352 * 288 video quality . how can i update it to support atleast 1280*720 video quality

		MediaFormatVideo mf=new MediaFormatVideo();
		mf.setFpsNum(30);
		mf.setFpsDenum(1);
		mf.setAvgBps(512000);
		mf.setMaxBps(1024000);
		mf.setHeight(720);
		mf.setWidth(1280);

i am updating those setting as below .

       MyCall call = new MyCall(account, -1);
        CallOpParam prm = new CallOpParam(true);
        AccountVideoConfig avc=new AccountVideoConfig();
        MediaFormatVideo mf=new MediaFormatVideo();

        Log.e("javan-video",String.valueOf(avc.getAutoShowIncoming()));
        Log.e("javan-videofps",String.valueOf(mf.getFpsNum()));
        mf.setFpsNum(30);
        mf.setFpsDenum(1);
        mf.setAvgBps(512000);
        mf.setMaxBps(1024000);
        mf.setHeight(720);
        mf.setWidth(1280);
        Log.e("javan-videofps",String.valueOf(mf.getFpsNum()));

        try {
            call.makeCall("sip:"+dialno+"@peoplefone.ch", prm);
            AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);

           am.setSpeakerphoneOn(true);

             // startRinging();

        } catch (Exception e) {
            call.delete();
            return;
        }

        currentCall = call;
     showCallActivity();
    }

**Comment by sauwming** [comment] 2023-03-16 03:12
Duplicate of #2615

**Closed by sauwming** 2023-03-16 03:12 UTC
Labels: type: enhancement
