### ISSUE TITLE
 File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module>     import _pjsua ImportError: DLL load failed: %1 is not a valid Win32 application. PS C:\Users\Administrator\Desktop\om> & C:/Python27/python.exe c:/Users/Administrator/Desktop/om/test.py Traceback (most recent call last):   File "c:/Users/Administrator/Desktop/om/test.py", line 1, in <module>     import pjsua   File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module>       import _pjsua ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by shubhamkar2104** [pjsip/pjproject#3967] opened 2024-05-23 05:02 UTC
### Describe the bug

i am getting this error while building the pjsua for python version 2.7 using mingw method on windows..how to solve this issue...thanks in advance

### Steps to reproduce

Followed steps :
1. build the pjsip lib using minge
cd /pjsip
./configure
make dep
make 
2. sideloaded the build lib in python 2.7(as 2.4 is not working for compiling anymore)
cd /pjsip/pjsip-apps/src/python
python setup.py build_ext -compiler=mingw32 install
3. successfully sideloaded lib in python
4.getting error when imported and run in vs code
 File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module>
    import _pjsua
ImportError: DLL load failed: %1 is not a valid Win32 application.
PS C:\Users\Administrator\Desktop\om> & C:/Python27/python.exe c:/Users/Administrator/Desktop/om/test.py
Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/om/test.py", line 1, in <module>
    import pjsua
  File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module>  
    import _pjsua
ImportError: DLL load failed: %1 is not a valid Win32 application.

### PJSIP version

2.11.1

### Context

this issue facing on windows platform as i needed it in windows so tried to find the solution for this error

### Log, call stack, etc

```shell
File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module>
    import _pjsua
ImportError: DLL load failed: %1 is not a valid Win32 application.
PS C:\Users\Administrator\Desktop\om> & C:/Python27/python.exe c:/Users/Administrator/Desktop/om/test.py
Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/om/test.py", line 1, in <module>
    import pjsua
  File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module>  
    import _pjsua
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by sauwming** [comment] 2024-05-28 05:19
Duplicate of #3957

**Closed by sauwming** 2024-05-28 05:19 UTC
