### ISSUE TITLE
Memory is not reclaimed

### ISSUE THREAD

**Issue by wangwangwawng** [pjsip/pjproject#2359] opened 2020-03-26 06:52 UTC
Use the swig_java_pjsua2 module to call pjsua_im_send () method 300 times per second concurrently. The test duration is 24 hours. After 24 hours, the physical memory is not released. If you continue to call pjsua_im_send (), the memory will increase slightly. How can I release it manually?

**Comment by sauwming** [comment] 2020-04-06 01:42
Duplicate of #2348

**Closed by sauwming** 2020-04-06 01:42 UTC
Labels: type: bug
