### ISSUE TITLE
Having an Error of Indentation

### ISSUE THREAD

**Issue by mishraranjan** [pjsip/pjproject#3711] opened 2023-09-20 07:28 UTC
### Describe the bug

 After giving all the commands I have mentioned below, the indentation error is coming.

### Steps to reproduce
#install depencies
apt install python-dev gcc make gcc binutils build-essential
#get pjsip
wget -O pjproject.tar.gz https://github.com/pjsip/pjproject/archive/2.13.1.tar.gz
tar -xvzf pjproject.tar.gz && mv pjproject-2.13.1 pjproject
cd pjproject
#configure
export CFLAGS="$CFLAGS -fPIC"

#build pjsip
./configure && make dep && make
#build python modules
cd pjsip-apps/src/python/
sudo python3 setup.py install

### PJSIP version

2.13.1

### Context

Issue happen on Linux Ubuntu

### Log, call stack, etc

 File "~/pjproject/pjsip-apps/src/python/setup.py", line 35
    if len(tokens)>1:
TabError: inconsistent use of tabs and spaces in indentation

**Comment by wosrediinanatour** [comment] 2023-09-20 09:31
What did you do before "sudo make install", i.e. what's your Bash history?

**Comment by mishraranjan** [comment] 2023-09-20 09:48
#install depencies
# apt install python-dev gcc make gcc binutils build-essential
#get pjsip
# wget -O pjproject.tar.gz
https://github.com/pjsip/pjproject/archive/2.13.1.tar.gz
# tar -xvzf pjproject.tar.gz && mv pjproject-2.13.1 pjproject
cd pjproject
#configure
export CFLAGS="$CFLAGS -fPIC"

#build pjsip
./configure && make dep && make
#build python modules
cd pjsip-apps/src/python/
sudo python3 setup.py install

These were the commands that I used

**Comment by mishraranjan** [comment] 2023-09-20 10:48
I have reframed my issues so please check it.

**Comment by sauwming** [comment] 2023-09-21 06:04
Duplicate of #3713

**Closed by sauwming** 2023-09-21 06:04 UTC
