### ISSUE TITLE
SRTP/DTLS Parse Error from Linphone

### ISSUE THREAD

**Issue by amubiera** [pjsip/pjproject#3852] opened 2024-02-05 23:38 UTC
### Describe the bug

Hello,

I'm placing DTLS-enabled calls from Linphone to my PJSIP-based application. Calls establish and audio appears to be flowing. However, I see SRTP parse errors every 1 second or so.

In `srtp.c`: `srtp_unprotect_mki` returns `srtp_err_status_parse_err` on line 2661 due to out of bound pointer.

In the failure case:
- hdr->cc == 0
- hdr->x == 0
- pkt_octet_len == 20
- tag_len == 10
- mki_size == 0

And the `enc_start` comparison fails by 2 bytes:
```
if (stream->rtp_services & sec_serv_conf) {
    enc_start = (pj_uint32_t *)hdr + uint32s_in_rtp_header + hdr->cc;
    if (hdr->x == 1) {
        xtn_hdr = (srtp_hdr_xtnd_t *)enc_start;
        enc_start += (ntohs(xtn_hdr->length) + 1);
    }
    if (!((uint8_t *)enc_start <=
            (uint8_t *)hdr + (*pkt_octet_len - tag_len - mki_size)))
        return srtp_err_status_parse_err;
    enc_octet_len = (pj_uint32_t)(*pkt_octet_len - tag_len - mki_size -
                                ((uint8_t *)enc_start - (uint8_t *)hdr));
} else {
    enc_start = NULL;
}
```

Do you have any clues on how to debug this? Is it a fault of Linphone or something with PJSIP ?

Notes:
- Calls between two PJSIP endpoints do not have this issue.
- This appears to be coming from the RTCP handshake.
- There is a minor typo in `error pasring data` error messages.

### Steps to reproduce

1. Call a PJSIP endpoint from Linphone with mandatory DTLS enabled.

### PJSIP version

2.14

### Context

- Linphone with DTLS mandatory

### Log, call stack, etc

```shell
18:22:35.276   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
18:22:35.797   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
18:22:36.309   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
18:22:36.792   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
18:22:37.313   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
18:22:37.818   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
18:22:38.337   srtp0x1ea758 !Failed to unprotect SRTP, pkt size=20, err=error pasring data
```

**Comment by nanangizz** [comment] 2024-02-06 04:52
Looks like the packet is not an SRTP packet, RTP header length is 12 octets, the SRTP tag in the context needs 10 octets (as specified by `tag_len`), so an RTP packet should be at least 22 octets (for empty payload). But not sure if it is an RTCP packet either, as RTCP packet should be parsed/processed by SRTCP (e.g: message should be "Failed to unprotect SRTCP...", the PJMEDIA transport should be able to differentiate them when RTCP-mux is enabled. So perhaps you can check the payload type of the packet first.

Re: typo, just fixed this [here](https://github.com/pjsip/pjproject/pull/3853/commits/c70f1a35f0072618115daf28387d97d3b63cd209), thanks.

**Comment by amubiera** [comment] 2024-02-06 18:11
Thanks for the response, Nanang.

`srtp->use_rtcp_mux` is false, so there are two active UDP sockets (e.g. RTP=17 and RTCP=18). In this case, the device  has received the packet on the RTP socket 17.

The RTP channel DTLS negotiation has already completed but the RTCP channel negotiation is still on-going, so it seems to be related to RTCP.

When the parse error happens, the `srtp_hdr_t` header is:
- p == 0
- version == 0
- pt == 1
- m == 0
- seq = 0
- ts = 1118048801
- ssrc = 246010132

Does that packet look off?

**Comment by nanangizz** [comment] 2024-02-07 01:49
Yes, it looks off to me. The `version = 0` indicates that it is neither RTP nor RTCP, as mandated by standard, it should be 2 (perhaps we can add this check in media transports). Also `pt = 1` and `m = 0`, it does not look like an RTCP packet. Note that RTCP normally uses a higher PT, i.e: >= 200, or if parsed as RTP, the marker bit is usually 1 or `m = 1`, see [here](https://www.rfc-editor.org/rfc/rfc3550#section-12.1).

It may be a DTLS packet (need to check the first byte, see [here](https://datatracker.ietf.org/doc/html/rfc5764#section-5.1.2)), but I guess DTLS nego for RTCP should be done on the RTCP socket. Perhaps it is kind of Linphone proprietary packet. Anyway as audio/RTP packets seem to flow just fine, I guess it is safe to just ignore them for now?

**Comment by andreas-wehrmann** [comment] 2024-02-07 14:44
@amubiera 
Did you capture traffic with i.e. Wirshark and took a look at those "interesting" packets?
Maybe you can discern from that what's actually being transmitted.
Could they be STUN requests? Wireshark might be able to tell you.

**Comment by amubiera** [comment] 2024-02-07 14:47
> I guess it is safe to just ignore them for now?

The DTLS handshake for the RTCP channel doesn't seem to be completing. So Linphone believes that the call is not encrypted. It'll be good to figure out why.

@andreas-wehrmann That's a good idea. It'll be my next step.

**Comment by amubiera** [comment] 2024-02-07 21:08
@andreas-wehrmann they are indeed STUN packets.

```
Frame 294: 62 bytes on wire (496 bits), 62 bytes captured (496 bits) on interface en0, id 0
User Datagram Protocol, Src Port: 60447, Dst Port: 4000
    Source Port: 60447
    Destination Port: 4000
    Length: 28
    Checksum: 0x8552 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 1]
    [Timestamps]
        [Time since first frame: 2.616425000 seconds]
        [Time since previous frame: 0.009065000 seconds]
    UDP payload (20 bytes)
Session Traversal Utilities for NAT
    Message Type: 0x0001 (Binding Request)
        .... ...0 ...0 .... = Message Class: 0x00 Request (0)
        ..00 000. 000. 0001 = Message Method: 0x0001 Binding (0x001)
        ..0. .... .... .... = Message Method Assignment: IETF Review (0x0)
    Message Length: 0
    Message Cookie: 2112a442
    Message Transaction ID: 99649ca1be7804e432ef3404
```

I wonder if this would prevent DTLS handshake for RTCP to not complete. Maybe that is an unrelated issue.

**Comment by amubiera** [comment] 2024-02-07 22:10
Enabling `enable_rtcp_mux` in the account config allows Linphone recognize that the connection is encrypted with DTLS. But it still receives the parse error for STUN packets. So these two issues may be unrelated.

**Comment by sauwming** [comment] 2024-02-13 03:45
I just tested with Linphone and didn't encounter the issue you described.
And actually, when implementing #3571, I used Linphone to test with.

Here the log will show like this:
```
11:40:13.944        dtls0x110cf7880 !DTLS-SRTP negotiation for RTP channel completed!
11:40:14.057        srtp0x10e966880  SRTP started, keying=DTLS-SRTP, crypto=AES_CM_128_HMAC_SHA1_80
11:40:14.057          pjsua_media.c  Call 2: Media 0: SRTP negotiation completes: Success
11:40:14.057        dtls0x110cf7880  DTLS-SRTP negotiation for RTCP channel completed!
```
And on the Linphone side, I can see the green shield with the status text "Call is encrypted with: DTLS".

Perhaps there are specific config that triggers the issue? Perhaps you can try disabling STUN? I tried enabling ICE and STUN here but there doesn't seem to be any issue as well.

**Comment by amubiera** [comment] 2024-02-13 14:05
Thanks for testing it out. I will try without STUN.

What is the easiest sample app to build with my configuration? I'd like to try connecting Linphone to a simple PJSIP-based client with my config, rather than using my app.

**Comment by amubiera** [comment] 2024-02-28 23:52
I was able to reproduce the issue using `simple_pjsua.c` compiled for MacOS homebrew.

_Side issue:_
Everything compiles with OpenSSLv3: `./configure --with-ssl=/opt/homebrew/Cellar/openssl@3/3.2.1/`
but not with OpenSSLv1.1.1: `./configure --with-ssl=/opt/homebrew/Cellar/openssl@1.1/1.1.1w/`
It gets the following link error:
```
ld: Undefined symbols:
  _SSL_get_peer_certificate, referenced from:
      _ssl_match_fingerprint in libpjmedia-arm-apple-darwin23.3.0.a[57](transport_srtp.o)
      _update_certs_info in libpj-arm-apple-darwin23.3.0.a[44](ssl_sock_ossl.o)
```

_DTLS issue:_
* I modified the sample a bit to have the account registration match my app:
  * Use PJSIP_TRANSPORT_TLS with port 5061.
  * Use pjsua_acc_config.proxy to separate the domain from the endpoint.
* With RTCP mux enabled, Linphone shows the connection is encrypted.
* With RTCP mux disabled, Linphone shows the red icon for unencrypted.
* Linphone is the caller and the sample app is the callee.
* I saved logs for both runs. I will attach them here with some info redacted.
* In the failing case, I see the `DTLS-SRTP negotiation for RTP channel completed!` but not for RTCP.

Since the Kamailio server I'm using is not on the same network, perhaps this is an issue with NAT. I don't have control over that server, so I'll ask the admin for help.

I will also try standing up my own Freeswitch server on my subnet to see if it has the same issue.

But in the meantime, do you have any clues?

p.s. you can see the STUN parse errors in the log:
`!Failed to unprotect SRTP, pkt size=20, err=error pasring data`

Logs:
[2024-02-28-dtls-rtcp-mux-disabled.log](https://github.com/pjsip/pjproject/files/14441025/2024-02-28-dtls-rtcp-mux-disabled.log)
[2024-02-28-dtls-rtcp-mux-enabled.log](https://github.com/pjsip/pjproject/files/14441026/2024-02-28-dtls-rtcp-mux-enabled.log)

**Comment by sauwming** [comment] 2024-02-29 02:36
I tested with the same scenario here (Linphone 5.0.15 caller vs pjsua) and it seems to work fine.

Some suggestions:
- Use pjsua, instead of simple pjsua. This way you don't need to modify the sample app. To achieve the same setup as you describe, you just need to pass the options:
```
--use-tls
--id=[id]
--realm=*
--username=[username]
--password=[passwd]
--registrar=sip:[registrar];transport=tls
--proxy=sip:[proxy];transport=tls
--auto-answer=200
--use-srtp=2
--srtp-secure=0
--srtp-keying=1
```
- Enable `DTLS_DEBUG` in `transport_srtp_dtls.c`. It should give you information of the DTLS handshake progress in the log, such as:
```
dtls0x109a98880  ..Attached transport, remote addr=..., remote rtcp=...
10:26:37.811        dtls0x109a98880 !DTLS-SRTP RTP channel receiving 1239 bytes
10:26:37.812        dtls0x109a98880  DTLS-SRTP RTP channel receiving 581 bytes
10:26:37.837        dtls0x109a98880  DTLS-SRTP RTP channel sending 1338 bytes
10:26:37.837        dtls0x109a98880  DTLS-SRTP RTP channel receiving 1239 bytes
10:26:37.837        dtls0x109a98880  DTLS-SRTP RTP channel receiving 581 bytes
10:26:37.837        dtls0x109a98880  DTLS-SRTP RTCP channel receiving 1239 bytes
10:26:37.837        dtls0x109a98880  DTLS-SRTP RTCP channel receiving 581 bytes
10:26:37.843        dtls0x109a98880  DTLS-SRTP RTCP channel sending 1338 bytes
10:26:37.843        dtls0x109a98880  DTLS-SRTP RTCP channel receiving 1239 bytes
10:26:37.843        dtls0x109a98880  DTLS-SRTP RTCP channel receiving 581 bytes
10:26:37.843        dtls0x109a98880  DTLS-SRTP RTP channel receiving 67 bytes
10:26:37.843        dtls0x109a98880  DTLS-SRTP negotiation for RTP channel completed!
10:26:37.890        srtp0x1098f0080  SRTP started, keying=DTLS-SRTP, crypto=AES_CM_128_HMAC_SHA1_80
10:26:37.890          pjsua_media.c  Call 0: Media 0: SRTP negotiation completes: Success
10:26:37.890        dtls0x109a98880  DTLS-SRTP RTCP channel receiving 67 bytes
10:26:37.890        dtls0x109a98880  DTLS-SRTP negotiation for RTCP channel completed!
```

**Comment by sauwming** [comment] 2024-03-01 05:27
Not sure where the problem was, but it seems that the remote didn't respond to the RTCP handshake:
```
17:48:42.842         udp0x134d06710  Remote RTCP address switched to 172.16.226.43:55380
17:48:45.007        dtls0x12501e600 !DTLS-SRTP RTCP channel sending 222 bytes
17:48:53.008        dtls0x12501e600 !DTLS-SRTP RTCP channel sending 222 bytes
```
Perhaps you can attach us the complete PJSIP log.

You may also want to check Linphone log (in Linphone-Advanced-Logs, clean the logs first) if they indicate any error.

**Comment by amubiera** [comment] 2024-03-01 20:22
I captured full logs for both sides. See attached.

There are various warnings in the Linphone logs. Like this:
```
2024-03-01 15:05:38:971 [linphone/ortp] WARNING RtpSession [0x7f7cfe690e00] receiving rtcp packet with version number != 2, discarded
```
[2024-03-01-dtls-negotiation-linphone-01.log](https://github.com/pjsip/pjproject/files/14465564/2024-03-01-dtls-negotiation-linphone-01.log)
[2024-03-01-dtls-negotiation-pjsua-01.log](https://github.com/pjsip/pjproject/files/14465565/2024-03-01-dtls-negotiation-pjsua-01.log)

**Comment by sauwming** [comment] 2024-03-04 06:03
I can reproduce the issue with Linphone 5.2.1 (note that as mentioned previously, the issue didn't happen with Linphone 5.0.15).

And I received the same warning as yours:
```
2024-03-04 13:39:57:339 [linphone/mediastreamer] MESSAGE DTLS Receive RTP packet len 216 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400
2024-03-04 13:39:57:339 [linphone/mediastreamer] MESSAGE DTLS Send RTP packet len 1239 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400
2024-03-04 13:39:57:339 [linphone/mediastreamer] MESSAGE DTLS Send RTP packet len 476 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400
2024-03-04 13:39:57:339 [linphone/mediastreamer] MESSAGE DTLS Handshake process RTP packet len 216 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400 return -0x70032000
2024-03-04 13:39:57:339 [linphone/ortp] WARNING RtpSession [0x7f92fc18a400] receiving rtcp packet with version number != 2, discarded
2024-03-04 13:39:57:349 [linphone/mediastreamer] MESSAGE DTLS Receive RTP packet len 1237 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400
2024-03-04 13:39:57:350 [linphone/mediastreamer] MESSAGE DTLS Send RTP packet len 67 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400
2024-03-04 13:39:57:350 [linphone/mediastreamer] MESSAGE DTLS Handshake process RTP packet len 1237 sessions: 0x7f92fc8a2d58 rtp session 0x7f92fc18a400 return -0x0
2024-03-04 13:39:57:350 [linphone/mediastreamer] MESSAGE DTLS Handshake on RTP channel successful, srtp protection profile 1
```

I can't be 100% certain since I'm not familiar with Linphone, but from the log, it seems that the bug is on their side.

The warning `receiving rtcp packet with version number != 2, discarded` indicated the incorrect action, because the packet is actually not a rtcp packet, but a DTLS handshake packet, which they previously (on Linphone version 5.0.15 at least) could process just fine.

So I believe they should not discard the packet, and proceed with the handshake for the RTCP instead.

As a workaround for now, you can use the previous versions of Linphone instead:
https://download.linphone.org/releases/macosx/app/

**Comment by amubiera** [comment] 2024-03-04 15:34
Thanks for testing with the older version. I can try to post the issue to their mailing list. And close it here.

Re: the STUN parse errors on the PJSIP side. Is that something that will eventually be supported or just safe to ignore?

**Comment by sauwming** [comment] 2024-03-05 03:20
The error `Failed to unprotect` naturally will appear if the handshake fails. Since the key negotiation fails, we obviously won't be able to decrypt the packet.

**Comment by sauwming** [comment] 2024-03-12 02:35
> Thanks for testing with the older version. I can try to post the issue to their mailing list. And close it here.

Alright, I will close the issue. Feel free to let us know if further investigation reveals any incorrect behavior on our part that needs to be rectified.

**Closed by sauwming** 2024-03-12 02:35 UTC
