### ISSUE TITLE
Too many objects of the specified type (PJ_ETOOMANY) [status=70010]

### ISSUE THREAD

**Issue by tangxiangpi** [pjsip/pjproject#2444] opened 2020-05-21 08:22 UTC
on android 10 huawei pjsip 2.9.
when app is on background for a long time may 30m,but sometimes ....SIP registration failed, status=503 (Too many objects of the specified type (PJ_ETOOMANY) [status=70010],how can i avoid this problem ？
can i increase PJ_IOQUEUE_MAX_HANDLES to avoid this problem?
[core_20200423.xlog.log](https://github.com/pjsip/pjproject/files/4661344/core_20200423.xlog.log)

**Comment by Truong-Thanh-Quang** [comment] 2020-06-04 04:05
You are calling pjsua_acc_add() too many times.
Only call once for each account.

**Comment by nanangizz** [comment] 2020-06-26 08:03
Sounds like a duplicate of this: https://github.com/pjsip/pjproject/pull/2357, please check.
Closing this issue for now. If problem persists, please provide more detail info, e.g: reproducing steps with pjsua sample app.

**Closed by nanangizz** 2020-06-26 08:03 UTC
Labels: type: bug

**Comment by tangxiangpi** [comment] 2020-07-05 12:49
> Sounds like a duplicate of #2400, also please check PR #2357, which seems to be the fix of this issue.
> 
> Closing this issue for now. If problem persists, please provide more detail info, e.g: reproducing steps with pjsua sample app.

i have already attach log , and i checked pr #2357,but it still happened on android 10 huawei pjsip 2.9 , put the phone background for a while ,
