### ISSUE TITLE
Reregister of pjsua2 stops suddenly

### ISSUE THREAD

**Issue by ilogixxDE** [pjsip/pjproject#3218] opened 2022-08-18 10:29 UTC
### Describe the bug

We use pjsua in our app which is connected to the pbx all time. Normally we see that every 2 minutes a reregister is perfomed and that works well. But in rare cases, the library does not send the regsiter message after the 2 minutes any more and stops sendinf register at all. So we need to restart the app to get it registered again. 
So, potentially there is somehow a bug in the library that stops the reregsitrations. Or we do something wrong which stops reregistrations. So can you please help us to get that sorted?
In the trace file, we see only that no more register messages are emitted from pjsua.

Maybe a workaround exists for our app to get that serted?

Thanks

### Steps to reproduce

It may take days or week untill the reregistering fails

### PJSIP version

2.12

### Context

windows server 2019/2022

### Log, call stack, etc

```shell
No meaningfull log
```

**Comment by AntonYashin** [comment] 2023-01-16 21:10
@ilogixxDE Did you solve it? Have a same issue.

**Comment by medvel** [comment] 2023-02-26 09:38
Hello, we have quite similar problems [(https://github.com/pjsip/pjproject/issues/3406)]. In our case first registration is successful, but all others are not. It looks like server stops responding to our messages.

What server do you use?

**Comment by wosrediinanatour** [comment] 2023-02-26 09:56
> Hello, we have quite similar problems [(https://github.com/[/issues/3406](https://github.com/pjsip/pjproject/issues/3406))]. In our case first registration is successful, but all others are not. It looks like server stops responding to our messages.
> 
> What server do you use?

It is different - because in yourcase, PJSUA2 does reregister.

For this issue, logs a required.

**Comment by medvel** [comment] 2023-02-26 16:58
> > Hello, we have quite similar problems [(https://github.com/[/issues/3406](https://github.com/pjsip/pjproject/issues/3406))]. In our case first registration is successful, but all others are not. It looks like server stops responding to our messages.
> 
> It is different - because in your case, PJSUA2 does reregister.

In my case it doesn't re-register. Please take a look at  [(https://github.com/[/issues/3406](https://github.com/pjsip/pjproject/issues/3406))].

**Comment by sauwming** [comment] 2023-04-04 03:19
The issue is being resolved via another channel.

**Closed by sauwming** 2023-04-04 03:19 UTC
