### ISSUE TITLE
PJSIP with call audio capturing and streaming features

### ISSUE THREAD

**Issue by stealth-program** [pjsip/pjproject#2700] opened 2021-04-19 17:27 UTC
I want to use pjsip java wrapper with discord client. So I need to get pcm frames and put pcm frames to audio stream (pcm bytes). Everyone needs this feature.
Moreover, there is some implementation of that feature: https://github.com/isabyr/pjsipstreamer . Unfortunately, this works only in plain c++ and Python, not Java. Can you please merge that feature in your master branch?

**Comment by sauwming** [comment] 2023-04-06 06:26
True, this seems to be quite a popular request. Duplicate of #2352 so any update will be posted there instead.

**Closed by sauwming** 2023-04-06 06:26 UTC
Labels: type: enhancement
