### ISSUE TITLE
Python Audio Callback implemented in the official project

### ISSUE THREAD

**Issue by nicolaipre** [pjsip/pjproject#2418] opened 2020-05-02 13:09 UTC
For the past six months I have been working on a dirty patch for Audio Callbacks/Streaming with pjsip for Python 3 and almost got it working. 

Today however, I found this patch made by someone else in 2013, which apparently had implemented exactly the functionality I need: http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2013-March/015863.html

I also found an updated patch (2014) by the same person here: https://www.spinics.net/lists/pjsip/msg17592.html

I could not find any signs this has been implemented in the official project yet. As my current personal project consists of relaying audio, this would be great to have. 

Is this something that could be added as a feature (possibly also without locking, to get true real-time audio transmission)?

**Comment by sauwming** [comment] 2020-05-18 07:56
This issue is related to #2352 .

There seems to be a few requests about this recently. Unfortunately, we have set out our roadmap for version 2.11 and this is not included. But it seems that you have some success with it already. If you think that it can be merged into `master` branch, feel free to create a PR.

**Comment by nicolaipre** [comment] 2020-05-18 08:01
Thank you for the feedback @sauwming. 

I did indeed have success with @malarinv's [fork (branch: py37)](https://github.com/malarinv/pjproject/tree/py37). I do not want to take the credit for such a PR since it is @malarinv's work. Perhaps he would like to create the PR?

**Comment by sauwming** [comment] 2020-05-19 04:10
I have put your request in our wish list. Although as mentioned previously, with our current predefined roadmap, it's safe to assume that it won't be available in the near future (unless somebody managed to implement it and put a PR). Since this issue is a duplicate of #2352, I will close this and leave the other one open.

**Closed by sauwming** 2020-05-19 04:10 UTC
Labels: type: enhancement
