### ISSUE TITLE
Windows ioqueue backend missing pj_ioqueue_register_sock2

### ISSUE THREAD

**Issue by ddv2005** [pjsip/pjproject#2888] opened 2021-11-17 06:04 UTC
### Describe the bug

Windows ioqueue backend is outdated and missing pj_ioqueue_register_sock2 function. By default pjlib use select backend for ioqueue but it is limited to 64 handles and very slow. IO Completion backend is ideal for Windows but it is not updated for years and incompatible with current release that needs pj_ioqueue_register_sock2

### Steps to reproduce

1. Enable ioqueue_winnt.c instead of ioqueue_select.c in pjlib project.
2. Build pjsua apps
3. Build failed because of missing pj_ioqueue_register_sock2

### PJSIP version

2.11

### Context

Windows 10

### Log, call stack, etc

```shell
2>pjlib-util-i386-Win32-vc14-Release-Static.lib(resolver.obj) : error LNK2019: unresolved external symbol _pj_ioqueue_register_sock2 referenced in function _pj_dns_resolver_create
2>pjnath-i386-Win32-vc14-Release-Static.lib(nat_detect.obj) : error LNK2001: unresolved external symbol _pj_ioqueue_register_sock2
2>pjsip-core-i386-Win32-vc14-Release-Static.lib(sip_transport_udp.obj) : error LNK2001: unresolved external symbol _pj_ioqueue_register_sock2
2>pjlib-i386-Win32-vc14-Release-Static.lib(activesock.obj) : error LNK2001: unresolved external symbol _pj_ioqueue_register_sock2
```

**Comment by sauwming** [comment] 2023-02-02 11:45
Duplicate of #3291. Will fix the other one soon.

**Closed by sauwming** 2023-02-02 11:45 UTC
