### ISSUE TITLE
Generate some dll or Wrapper for c #

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2302] opened 2020-02-24 16:32 UTC
@sauwming Hello, i wanted to know if there was any possibility or if you had any way of being able to generate a wrapper or some dll based on PJSUA app, that the truth is the best I've seen, and I wanted to know if there was any way to generate a dll or a wrapper. Or if there is any way I can generate it, can you tell me.

Thank you I will wait for your answer

**Comment by sauwming** [comment] 2020-02-25 02:59
Duplicate of #2299.
Please avoid opening new issues for same/similar topics. Thanks.

**Closed by sauwming** 2020-02-25 02:59 UTC
