### ISSUE TITLE
Crash pjsua_call_answer_with_sdp.cold.1

### ISSUE THREAD

**Issue by muhammadjon-swift** [pjsip/pjproject#3977] opened 2024-05-31 07:04 UTC
### Describe the bug

Assertion when answering incoming call 

### Steps to reproduce

call

### PJSIP version

2.14.1

### Context

iOS 
config
#define PJ_CONFIG_IPHONE 1 
#define PJMEDIA_HAS_VIDEO 1 // enabling video
#define PJMEDIA_HAS_VID_TOOLBOX_CODEC 1
#define PJ_HAS_SSL_SOCK 1 // enabling ssl 
##define PJ_SSL_SOCK_IMP PJ_SSL_SOCK_IMP_APPLE
#include <pj/config_site_sample.h> 

### Log, call stack, etc

```shell
Assertion failed: (call_id>=0 && call_id<(int)pjsua_var.ua_cfg.max_calls), function pjsua_call_answer2, file pjsua_call.c, line 2738.

I believe I understand the error I have all the checks to prevent a crash but it still crashes. I'm handling errors and checking if callId is not invalid or exceeds max calls

 Answer incoming call
 */
bool PJSua2::answerCall()
{    
    if (call == NULL) {
        printLog("call is null in answerCall");
        return false;
    }
    if (call->getId() == PJSUA_INVALID_ID) { return false; }
    if (call->getId() >= maxCalls) { return false; }
    
    CallOpParam op(true);
    op.opt.audioCount = 1;
    op.statusCode = PJSIP_SC_OK;
    try {
        call->answer(op);
        return true;
    } catch(Error& err) {
        printLog("ANSWER_CALL: Error: " + err.info() );
        return false;
    }
}
```

**Comment by sauwming** [comment] 2024-05-31 11:03
You can run it under a debugger to check the call id value (not sure how you get maxCalls but perhaps maxCalls is different than the one in pjsua_var?)

Also, inspect the log to check if the call has been cancelled/disconnected.

**Comment by muhammadjon-swift** [comment] 2024-06-06 06:17
> You can run it under a debugger to check the call id value (not sure how you get maxCalls but perhaps maxCalls is different than the one in pjsua_var?)
> 
> Also, inspect the log to check if the call has been cancelled/disconnected.

I was not able to catch the crash my self however this is the most common crash among our users

**Comment by sauwming** [comment] 2024-06-18 00:32
Closing due to insufficient information. Just let us know if you can obtain more details, such as the log or reproducing steps.

**Closed by sauwming** 2024-06-18 00:32 UTC
