### ISSUE TITLE
pjsip2.14 preVideo displays a screen with a green filter

### ISSUE THREAD

**Issue by LoyaiHai** [pjsip/pjproject#3762] opened 2023-11-03 01:24 UTC
### Describe the bug

When I successfully compiled pjsip2.14, generated armeabi-v7a and arm64-v8a, and ported them to AndroidStudio, I found that the previewed front camera displayed a picture like a green filter

### Steps to reproduce

1、cp source resource to androidstudio
     Ubuntu source resource:
2、jniLibs path: libpjsua2.so===>pjproject-2.14/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a
      pjsip java code: org.pjsip code===>pjproject-2.14/pjsip-apps/src/swig/java/android/pjsua2/src/main/java
      pjsip java app code: app->MyApp.java...===>pjproject-2.14/pjsip-apps/src/swig/java/android/app/src/main/java/org/pjsip/pjsua2/app
 
Above code and resource, when cp to AndroidStudio, none of which has been modified。

### PJSIP version

2.14

### Context

Windows: Android Studio Dolphin | 2021.3.1 Patch 1
android phone 8.1

### Log, call stack, etc

```shell
/* $Id: MyApp.java 5361 2016-06-28 14:32:08Z nanang $ */
/*
 * Copyright (C) 2013 Teluu Inc. (http://www.teluu.com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package org.pjsip.pjsua2.app;

import android.util.Log;

import java.io.File;
import java.util.ArrayList;

import org.pjsip.pjsua2.*;


/* Interface to separate UI & engine a bit better */
interface MyAppObserver
{
    abstract void notifyRegState(int code, String reason, long expiration);
    abstract void notifyIncomingCall(MyCall call);
    abstract void notifyCallState(MyCall call);
    abstract void notifyCallMediaState(MyCall call);
    abstract void notifyBuddyState(MyBuddy buddy);
    abstract void notifyChangeNetwork();
    abstract void notifyCallMediaEvent(MyCall call, OnCallMediaEventParam prm);
}


class MyLogWriter extends LogWriter
{
    @Override
    public void write(LogEntry entry)
    {
        System.out.println(entry.getMsg());
    }
}


class MyCall extends Call
{
    public VideoWindow vidWin;
    public VideoPreview vidPrev;

    public boolean vidPrevStarted;

    MyCall(MyAccount acc, int call_id)
    {
        super(acc, call_id);
        vidWin = null;
        vidPrev = null;
        vidPrevStarted = false;
    }

    @Override
    public void onCallState(OnCallStateParam prm)
    {
        try {
            CallInfo ci = getInfo();
            if (ci.getState() == 
                pjsip_inv_state.PJSIP_INV_STATE_DISCONNECTED)
            {
                if (vidPrevStarted)
                    vidPrev.stop();

                MyApp.ep.utilLogWrite(3, "MyCall", this.dump(true, ""));
            }
        } catch (Exception e) {
        }
        
        // Should not delete this call instance (self) in this context,
        // so the observer should manage this call instance deletion
        // out of this callback context.
        MyApp.observer.notifyCallState(this);
    }

    @Override
    public void onCallMediaState(OnCallMediaStateParam prm)
    {
        CallInfo ci;
        try {
            ci = getInfo();
        } catch (Exception e) {
            return;
        }

        CallMediaInfoVector cmiv = ci.getMedia();

        for (int i = 0; i < cmiv.size(); i++) {
            CallMediaInfo cmi = cmiv.get(i);
            if (cmi.getType() == pjmedia_type.PJMEDIA_TYPE_AUDIO &&
                (cmi.getStatus() == 
                        pjsua_call_media_status.PJSUA_CALL_MEDIA_ACTIVE ||
                 cmi.getStatus() == 
                        pjsua_call_media_status.PJSUA_CALL_MEDIA_REMOTE_HOLD))
            {
                // connect ports
                try {
                    AudioMedia am = getAudioMedia(i);
                    MyApp.ep.audDevManager().getCaptureDevMedia().
                                                            startTransmit(am);
                    am.startTransmit(MyApp.ep.audDevManager().
                                     getPlaybackDevMedia());
                } catch (Exception e) {
                    System.out.println("Failed connecting media ports" +
                                       e.getMessage());
                    continue;
                }
            } else if (cmi.getType() == pjmedia_type.PJMEDIA_TYPE_VIDEO &&
                       cmi.getStatus() == pjsua_call_media_status.PJSUA_CALL_MEDIA_ACTIVE)
            {
                /* If videoPreview was started, stop it first in case capture device has changed */
                if (vidPrevStarted) {
                    try {
                        vidPrevStarted = false;
                        vidPrev.stop();
                        vidPrev.delete();
                        vidPrev = null;
                    } catch (Exception e) {}
                }

                if (cmi.getVideoIncomingWindowId() != pjsua2.INVALID_ID)
                    vidWin = new VideoWindow(cmi.getVideoIncomingWindowId());

                if ((cmi.getDir() & pjmedia_dir.PJMEDIA_DIR_ENCODING) != 0) {
                    vidPrev = new VideoPreview(cmi.getVideoCapDev());
                    if (!vidPrevStarted) {
                        try {
                            Log.e("023===>", "这里说明跑到是预览这里来了");
                            vidPrev.start(new VideoPreviewOpParam());
                            vidPrevStarted = true;
                        } catch (Exception e) {
                            System.out.println("Failed start video preview" +
                                e.getMessage());
                            continue;
                        }
                    }
                }
            }
        }

        MyApp.observer.notifyCallMediaState(this);
    }

    @Override
    public void onCallMediaEvent(OnCallMediaEventParam prm) {
        MyApp.observer.notifyCallMediaEvent(this, prm);
    }
}


class MyAccount extends Account
{
    public ArrayList<MyBuddy> buddyList = new ArrayList<MyBuddy>();
    public AccountConfig cfg;

    MyAccount(AccountConfig config)
    {
        super();
        cfg = config;
    }

    public MyBuddy addBuddy(BuddyConfig bud_cfg)
    {
        /* Create Buddy */
        MyBuddy bud = new MyBuddy(bud_cfg);
        try {
            bud.create(this, bud_cfg);
        } catch (Exception e) {
            bud.delete();
            bud = null;
        }

        if (bud != null) {
            buddyList.add(bud);
            if (bud_cfg.getSubscribe())
                try {
                    bud.subscribePresence(true);
            } catch (Exception e) {}
        }

        return bud;
    }

    public void delBuddy(MyBuddy buddy)
    {
        buddyList.remove(buddy);
        buddy.delete();
    }

    public void delBuddy(int index)
    {
        MyBuddy bud = buddyList.get(index);
        buddyList.remove(index);
        bud.delete();
    }

    @Override
    public void onRegState(OnRegStateParam prm)
    {
        Log.e("023===>", "注册结果回调：" + prm.getCode() + ", 原因：" + prm.getReason());
        MyApp.observer.notifyRegState(prm.getCode(), prm.getReason(),
                                      prm.getExpiration());
    }

    @Override
    public void onIncomingCall(OnIncomingCallParam prm)
    {
        System.out.println("======== Incoming call ======== ");

        Log.e("023===>", "来电中getWholeMsg：" + prm.getRdata().getWholeMsg());
        Log.e("023===>", "来电中getInfo：" + prm.getRdata().getInfo());
        Log.e("023===>", "来电中getSrcAddress：" + prm.getRdata().getSrcAddress());

        MyCall call = new MyCall(this, prm.getCallId());
        MyApp.observer.notifyIncomingCall(call);
    }

    @Override
    public void onInstantMessage(OnInstantMessageParam prm)
    {
        System.out.println("======== Incoming pager ======== ");
        System.out.println("From     : " + prm.getFromUri());
        System.out.println("To       : " + prm.getToUri());
        System.out.println("Contact  : " + prm.getContactUri());
        System.out.println("Mimetype : " + prm.getContentType());
        System.out.println("Body     : " + prm.getMsgBody());
    }
}


class MyBuddy extends Buddy
{
    public BuddyConfig cfg;

    MyBuddy(BuddyConfig config)
    {
        super();
        cfg = config;
    }

    String getStatusText()
    {
        BuddyInfo bi;

        try {
            bi = getInfo();
        } catch (Exception e) {
            return "?";
        }

        String status = "";
        if (bi.getSubState() == pjsip_evsub_state.PJSIP_EVSUB_STATE_ACTIVE) {
            if (bi.getPresStatus().getStatus() ==
                pjsua_buddy_status.PJSUA_BUDDY_STATUS_ONLINE)
            {
                status = bi.getPresStatus().getStatusText();
                if (status == null || status.length()==0) {
                    status = "Online";
                }
            } else if (bi.getPresStatus().getStatus() == 
                       pjsua_buddy_status.PJSUA_BUDDY_STATUS_OFFLINE)
            {
                status = "Offline";
            } else {
                status = "Unknown";
            }
        }
        return status;
    }

    @Override
    public void onBuddyState()
    {
        MyApp.observer.notifyBuddyState(this);
    }

}


class MyAccountConfig
{
    public AccountConfig accCfg = new AccountConfig();
    public ArrayList<BuddyConfig> buddyCfgs = new ArrayList<BuddyConfig>();

    public void readObject(ContainerNode node)
    {
        try {
            ContainerNode acc_node = node.readContainer("Account");
            accCfg.readObject(acc_node);
            ContainerNode buddies_node = acc_node.readArray("buddies");
            buddyCfgs.clear();
            while (buddies_node.hasUnread()) {
                BuddyConfig bud_cfg = new BuddyConfig(); 
                bud_cfg.readObject(buddies_node);
                buddyCfgs.add(bud_cfg);
            }
        } catch (Exception e) {}
    }

    public void writeObject(ContainerNode node)
    {
        try {
            ContainerNode acc_node = node.writeNewContainer("Account");
            accCfg.writeObject(acc_node);
            ContainerNode buddies_node = acc_node.writeNewArray("buddies");
            for (int j = 0; j < buddyCfgs.size(); j++) {
                buddyCfgs.get(j).writeObject(buddies_node);
            }
        } catch (Exception e) {}
    }
}


class MyApp {
    static {
        try {
            Log.e("023===>", "开始加载===>pjsua2");
            System.loadLibrary("pjsua2");
            Log.e("023===>", "加载===>pjsua2  完成");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Failed to load native library pjsua2\n" + e);
            Log.e("023===>", "UnsatisfiedLinkError: " + e.getMessage());
        }

        Log.e("023===>", "开始加载===>c++_shared");
        System.loadLibrary("c++_shared");
        System.out.println("Library loaded");
        Log.e("023===>", "加载===>c++_shared  完成");

    }


    public static Endpoint ep = new Endpoint();
    public static MyAppObserver observer;
    public ArrayList<MyAccount> accList = new ArrayList<MyAccount>();

    private ArrayList<MyAccountConfig> accCfgs =
                                          new ArrayList<MyAccountConfig>();
    private EpConfig epConfig = new EpConfig();
    private TransportConfig sipTpConfig = new TransportConfig();
    private String appDir;

    /* Maintain reference to log writer to avoid premature cleanup by GC */
    private MyLogWriter logWriter;

    private final String configName = "pjsua2.json";
    private final int SIP_PORT  = 5060;
    private final int LOG_LEVEL = 4;

    public void init(MyAppObserver obs, String app_dir)
    {
        init(obs, app_dir, false);
    }

    public void init(MyAppObserver obs, String app_dir,
                     boolean own_worker_thread)
    {
        observer = obs;
        appDir = app_dir;

        /* Create endpoint */
        try {
            ep.libCreate();
        } catch (Exception e) {
            return;
        }

        long ecTailLen = epConfig.getMedConfig().getEcTailLen();
        long channelCount = epConfig.getMedConfig().getChannelCount();
        long audioFramePtime = epConfig.getMedConfig().getAudioFramePtime();
        int jbInit = epConfig.getMedConfig().getJbInit();
        long clockRate = epConfig.getMedConfig().getClockRate();
        long ecOptions = epConfig.getMedConfig().getEcOptions();
        boolean hasIoqueue = epConfig.getMedConfig().getHasIoqueue();
        long ilbcMode = epConfig.getMedConfig().getIlbcMode();
        int jbMax = epConfig.getMedConfig().getJbMax();
        int jbMinPre = epConfig.getMedConfig().getJbMinPre();
        int jbMaxPre = epConfig.getMedConfig().getJbMaxPre();
        long maxMediaPorts = epConfig.getMedConfig().getMaxMediaPorts();
        boolean noVad = epConfig.getMedConfig().getNoVad();
        long ptime = epConfig.getMedConfig().getPtime();
        long quality = epConfig.getMedConfig().getQuality();
        long rxDropPct = epConfig.getMedConfig().getRxDropPct();
        int sndAutoCloseTime = epConfig.getMedConfig().getSndAutoCloseTime();
        long threadCnt = epConfig.getMedConfig().getThreadCnt();
        boolean vidPreviewEnableNative = epConfig.getMedConfig().getVidPreviewEnableNative();

        Log.e("023===>", "这里媒体的配置===>"
                + "ecTailLen: " + ecTailLen // 回波消除器尾部长度，以毫秒为单位: 200
                + ", channelCount: " + channelCount // 1
                + ", audioFramePtime: " + audioFramePtime // 20
                + ", jbInit: " + jbInit // -1
                + ", clockRate: " + clockRate // 16000
                + ", ecOptions: " + ecOptions // 0
                + ", hasIoqueue: " + hasIoqueue // true
                + ", ilbcMode: " + ilbcMode // 30
                + ", jbMax: " + jbMax // -1
                + ", jbMinPre: " + jbMinPre // -1
                + ", jbMaxPre: " + jbMaxPre // -1
                + ", maxMediaPorts: " + maxMediaPorts // 12
                + ", noVad: " + noVad // false
                + ", ptime: " + ptime // 0
                + ", quality: " + quality // 4
                + ", rxDropPct: " + rxDropPct // 0
                + ", sndAutoCloseTime: " + sndAutoCloseTime // 1
                + ", threadCnt: " + threadCnt // 1
                + ", vidPreviewEnableNative: " + vidPreviewEnableNative // true
        );

//        /* Load config */
//        String configPath = appDir + "/" + configName;
//        File f = new File(configPath);
//        if (f.exists()) {
//            loadConfig(configPath);
//        } else {
//            /* Set 'default' values */
//            sipTpConfig.setPort(SIP_PORT);
//        }
//
//        /* Override log level setting */
//        epConfig.getLogConfig().setLevel(LOG_LEVEL);
//        epConfig.getLogConfig().setConsoleLevel(LOG_LEVEL);
//
//        /* Set log config. */
//        LogConfig log_cfg = epConfig.getLogConfig();
//        logWriter = new MyLogWriter();
//        log_cfg.setWriter(logWriter);
//        log_cfg.setDecor(log_cfg.getDecor() &
//                         ~(pj_log_decoration.PJ_LOG_HAS_CR |
//                         pj_log_decoration.PJ_LOG_HAS_NEWLINE));

        /* Write log to file (just uncomment whenever needed) */
        //String log_path = android.os.Environment.getExternalStorageDirectory().toString();
        //log_cfg.setFilename(log_path + "/pjsip.log");

        /* Set ua config. */
        UaConfig ua_cfg = epConfig.getUaConfig();
        ua_cfg.setUserAgent("Pjsua2 Android " + ep.libVersion().getFull());

        /* STUN server. */
        //StringVector stun_servers = new StringVector();
        //stun_servers.add("stun.pjsip.org");
        //ua_cfg.setStunServer(stun_servers);

        /* No worker thread */
        if (own_worker_thread) {
            ua_cfg.setThreadCnt(0);
            ua_cfg.setMainThreadOnly(true);
        }

        /* Init endpoint */
        try {
            ep.libInit(epConfig);
        } catch (Exception e) {
            return;
        }

        /* Create transports. */
        try {
            ep.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_UDP,
                               sipTpConfig);
        } catch (Exception e) {
            System.out.println(e);
        }

        try {
            ep.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_TCP,
                               sipTpConfig);
        } catch (Exception e) {
            System.out.println(e);
        }

//        try {
//            sipTpConfig.setPort(SIP_PORT+1);
//            ep.transportCreate(pjsip_transport_type_e.PJSIP_TRANSPORT_TLS,
//                               sipTpConfig);
//        } catch (Exception e) {
//            System.out.println(e);
//        }

        /* Set SIP port back to default for JSON saved config */
        sipTpConfig.setPort(SIP_PORT);

        /* Create accounts. */
        for (int i = 0; i < accCfgs.size(); i++) {
            MyAccountConfig my_cfg = accCfgs.get(i);

            /* Customize account config */
            my_cfg.accCfg.getNatConfig().setIceEnabled(true);
            my_cfg.accCfg.getVideoConfig().setAutoTransmitOutgoing(true);
            my_cfg.accCfg.getVideoConfig().setAutoShowIncoming(true);

            /* Enable SRTP optional mode and without requiring SIP TLS transport */
            my_cfg.accCfg.getMediaConfig().setSrtpUse(pjmedia_srtp_use.PJMEDIA_SRTP_OPTIONAL);
            my_cfg.accCfg.getMediaConfig().setSrtpSecureSignaling(0);

            MyAccount acc = addAcc(my_cfg.accCfg);
            if (acc == null)
                continue;

            /* Add Buddies */
            for (int j = 0; j < my_cfg.buddyCfgs.size(); j++) {
                BuddyConfig bud_cfg = my_cfg.buddyCfgs.get(j);
                acc.addBuddy(bud_cfg);
            }
        }

        /* Start. */
        try {
            ep.libStart();
        } catch (Exception e) {
            return;
        }

        Log.e("023===>", "这里的pjsip的版本号为：" + ep.libVersion().getFull());

        /* Also adjust encoding size in H264 to portrait 240x320 */
        try {
            CodecInfoVector2 codecs = ep.videoCodecEnum2();
            if (codecs != null) {
                Log.e("023===>", "这里的codecs的大小为：" + codecs.size());
            }
            String codecId = "H264/";


            for (CodecInfo c : codecs) {
                Log.e("023===>", "纯====》在判断前打印这里的codecId: " + c.getCodecId() + ", getPriority: " + c.getPriority() + ", getDesc: " + c.getDesc());
            }

            // codecId: H264/99
            // codecId: VP8/103
            for (CodecInfo c : codecs) {
                Log.e("023===>", "在判断前打印这里的codecId: " + c.getCodecId());
                if (c.getCodecId().startsWith(codecId)) {
                    codecId = c.getCodecId();
                    break;
                }
            }

            CodecInfoVector2 codecInfoVector2 = ep.videoCodecEnum2();
            if (codecInfoVector2 != null) {
                Log.e("023===>", "codecInfoVector2 != null");
            } else {
                Log.e("023===>", "codecInfoVector2 == null");
            }
            Log.e("023===>", "这里的: " + codecInfoVector2.size());
            for (int i = 0; i < codecInfoVector2.size(); i++) {
                Log.e("203===>", "这里的集合里面为===>getDesc：" + codecInfoVector2.get(i).getDesc());
                Log.e("203===>", "这里的集合里面为===>getCodecId：" + codecInfoVector2.get(i).getCodecId());
                Log.e("203===>", "这里的集合里面为===>getPriority：" + codecInfoVector2.get(i).getPriority());
            }


            VidCodecParam vcp = ep.getVideoCodecParam(codecId);

            // 看下这里的编码====>getWidth: 352
            // 看下这里的编码====>getHeight: 288
            // 看下这里的编码====>getFpsNum: 15
            // 看下这里的编码====>getFpsDenum: 1
            // 看下这里的编码====>getAvgBps: 256000
            // 看下这里的编码====>getMaxBps: 256000
            Log.e("023===>", "看下这里的编码====>getWidth: " + vcp.getEncFmt().getWidth());
            Log.e("023===>", "看下这里的编码====>getHeight: " + vcp.getEncFmt().getHeight());
            Log.e("023===>", "看下这里的编码====>getFpsNum: " + vcp.getEncFmt().getFpsNum());
            Log.e("023===>", "看下这里的编码====>getFpsDenum: " + vcp.getEncFmt().getFpsDenum());
            Log.e("023===>", "看下这里的编码====>getAvgBps: " + vcp.getEncFmt().getAvgBps());
            Log.e("023===>", "看下这里的编码====>getMaxBps: " + vcp.getEncFmt().getMaxBps());


            // 看下这里的解码====>getWidth: 352
            // 看下这里的解码====>getHeight: 288
            // 看下这里的解码====>getFpsNum: 15
            // 看下这里的解码====>getFpsDenum: 1
            // 看下这里的解码====>getAvgBps: 18247680
            // 看下这里的解码====>getMaxBps: 18247680
            Log.e("023===>", "看下这里的解码====>getWidth: " + vcp.getDecFmt().getWidth());
            Log.e("023===>", "看下这里的解码====>getHeight: " + vcp.getDecFmt().getHeight());
            Log.e("023===>", "看下这里的解码====>getFpsNum: " + vcp.getDecFmt().getFpsNum());
            Log.e("023===>", "看下这里的解码====>getFpsDenum: " + vcp.getDecFmt().getFpsDenum());
            Log.e("023===>", "看下这里的解码====>getAvgBps: " + vcp.getDecFmt().getAvgBps());
            Log.e("023===>", "看下这里的解码====>getMaxBps: " + vcp.getDecFmt().getMaxBps());

            vcp.getEncFmt().setWidth(480);
            vcp.getEncFmt().setHeight(640);
//
            vcp.getDecFmt().setAvgBps(512000);
            vcp.getDecFmt().setMaxBps(512000);

            CodecFmtpVector decFmtp = vcp.getDecFmtp();

            for (int i = 0; i < decFmtp.size(); i++) {
                Log.e("023===>", "看下这里的视频质量===>getName: " + decFmtp.get(i).getName());
                Log.e("023===>", "看下这里的视频质量===>getVal: " + decFmtp.get(i).getVal());
                if ("profile-level-id".equals(decFmtp.get(i).getName())) {
                    decFmtp.get(i).setVal("42e014");
                    break;
                }
            }

            vcp.setDecFmtp(decFmtp);

            ep.setVideoCodecParam(codecId, vcp);

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public MyAccount addAcc(AccountConfig cfg)
    {
        MyAccount acc = new MyAccount(cfg);
        try {
            acc.create(cfg);
        } catch (Exception e) {
            System.out.println(e);
            acc = null;
            return null;
        }

        accList.add(acc);
        return acc;
    }

    public void delAcc(MyAccount acc)
    {
        accList.remove(acc);
    }

    private void loadConfig(String filename)
    {
        JsonDocument json = new JsonDocument();

        try {
            /* Load file */
            json.loadFile(filename);
            ContainerNode root = json.getRootContainer();

            /* Read endpoint config */
            epConfig.readObject(root);

            /* Read transport config */
            ContainerNode tp_node = root.readContainer("SipTransport");
            sipTpConfig.readObject(tp_node);

            /* Read account configs */
            accCfgs.clear();
            ContainerNode accs_node = root.readArray("accounts");
            while (accs_node.hasUnread()) {
                MyAccountConfig acc_cfg = new MyAccountConfig();
                acc_cfg.readObject(accs_node);
                accCfgs.add(acc_cfg);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        /* Force delete json now, as I found that Java somehow destroys it
        * after lib has been destroyed and from non-registered thread.
        */
        json.delete();
    }

    private void buildAccConfigs()
    {
        /* Sync accCfgs from accList */
        accCfgs.clear();
        for (int i = 0; i < accList.size(); i++) {
            MyAccount acc = accList.get(i);
            MyAccountConfig my_acc_cfg = new MyAccountConfig();
            my_acc_cfg.accCfg = acc.cfg;

            my_acc_cfg.buddyCfgs.clear();
            for (int j = 0; j < acc.buddyList.size(); j++) {
                MyBuddy bud = acc.buddyList.get(j);
                my_acc_cfg.buddyCfgs.add(bud.cfg);
            }

            accCfgs.add(my_acc_cfg);
        }
    }

    private void saveConfig(String filename)
    {
        JsonDocument json = new JsonDocument();

        try {
            /* Write endpoint config */
            json.writeObject(epConfig);

            /* Write transport config */
            ContainerNode tp_node = json.writeNewContainer("SipTransport");
            sipTpConfig.writeObject(tp_node);

            /* Write account configs */
            buildAccConfigs();
            ContainerNode accs_node = json.writeNewArray("accounts");
            for (int i = 0; i < accCfgs.size(); i++) {
                accCfgs.get(i).writeObject(accs_node);
            }

            /* Save file */
            json.saveFile(filename);
        } catch (Exception e) {}

        /* Force delete json now, as I found that Java somehow destroys it
        * after lib has been destroyed and from non-registered thread.
        */
        json.delete();
    }

    public void handleNetworkChange()
    {
        try{
            System.out.println("Network change detected");
            IpChangeParam changeParam = new IpChangeParam();
            ep.handleIpChange(changeParam);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void deinit()
    {
        String configPath = appDir + "/" + configName;
        saveConfig(configPath);

        /* Try force GC to avoid late destroy of PJ objects as they should be
        * deleted before lib is destroyed.
        */
        Runtime.getRuntime().gc();

        /* Shutdown pjsua. Note that Endpoint destructor will also invoke
        * libDestroy(), so this will be a test of double libDestroy().
        */
        try {
            ep.libDestroy();
        } catch (Exception e) {}

        /* Force delete Endpoint here, to avoid deletion from a non-
        * registered thread (by GC?). 
        */
        ep.delete();
        ep = null;
    }
}
```

**Comment by sauwming** [comment] 2023-11-03 03:53
Test it with our sample app first, before creating your own application.

If it's fine with our sample app, it means something went wrong when you're copying stuffs.

**Comment by LoyaiHai** [comment] 2023-11-03 09:05
> Test it with our sample app first, before creating your own application.
> 
> If it's fine with our sample app, it means something went wrong when you're copying stuffs.

I used the faulty device and other mobile devices respectively, and found that the faulty device belonged to a customized Android device, and there was no problem when openh264/97 was used, but when using the latest pjsip2.14, the device obtained was openh264/99, and this problem occurred

**Comment by sauwming** [comment] 2023-11-03 13:58
So if I understand correctly, the problem is due to a faulty device? I will close this then

**Closed by sauwming** 2023-11-03 13:58 UTC
