### ISSUE TITLE
PJCamera.java bug (Android)

### ISSUE THREAD

**Issue by scottishdeveloper** [pjsip/pjproject#2334] opened 2020-03-06 11:07 UTC
1. Rotate the camera to back facing
2. Destroy the call (hangup)
3. Destroy camera preview
4. PJCamera -> Stop() is never called

Subsequent attempts to acquire the camera with further calls will fail with a -10 error, due to Camera in use.

This results in the Camera being locked forever and never "released", until an application force restart.

All versions up to 2.9,  not tested latest dev branches.

**Comment by sauwming** [comment] 2020-04-06 06:15
Please check #2368 and let us know if the issue is not resolved by that PR.

**Closed** 2020-04-29 03:00 UTC
Labels: type: bug
